import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

/**
 * Root layout component for the application.
 * Wraps the application content with ReduxProvider and includes common elements like Navbar.
 * @param children - The child components to be rendered within the layout.
 * @returns React component representing the root layout.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ReduxProvider } from "../provider/ReduxProvider";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
